# This file was initially generated by the serverspec gem command
# 'serverspec-init'. It has been heavily modified from the original.

require 'serverspec'
require 'net/ssh'
require 'tempfile'

set :backend, :ssh

host = ENV['TARGET_HOST']

puts "Running 'vagrant up' for '#{host}'..."

start_time = Time.now
output = `vagrant up #{host}`
end_time = Time.now

unless $?.success?
  puts "There was a problem while running 'vagrant up'!"

  puts '--------vagrant output------------'
  puts output
  puts '----------------------------------'
  exit 1
end

puts "'vagrant up' complete (took #{end_time - start_time}) seconds"


puts "Running 'vagrant provision' for '#{host}'..."

start_time = Time.now
output = `vagrant provision #{host}`
end_time = Time.now

unless $?.success?
  puts "There was a problem while running 'vagrant provision'!"

  puts '--------vagrant output------------'
  puts output
  puts '----------------------------------'
  exit 1
end

puts "'vagrant provision' complete (took #{end_time - start_time}) seconds"


config = Tempfile.new('', Dir.tmpdir)
config.write(`vagrant ssh-config #{host}`)
config.close

options = Net::SSH::Config.for(host, [config.path])

options[:user] ||= 'vagrant'
set :host, options[:host_name] || host
set :ssh_options, options
